name: Push CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'README.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: 0
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: Build with Gradle
      id: build
      env:
        KEYSTORE_PATH: "../keystore.jks"
        KEYSTORE_PASSWORD: zxc9870
        KEY_ALIAS: libra
        KEY_PASSWORD: zxc9870
      run: |
        echo 'org.gradle.jvmargs=-Xmx3072m' >> gradle.properties
        echo "/u3+7QAAAAIAAAABAAAAAQAFbGlicmEAAAGJEgj4PQAABQIwggT+MA4GCisGAQQBKgIRAQEFAASCBOrKlnV6w/oLp/kyYIYTfuMm190IxID3bMp0JmpqBbadqUOY9BZbPrvIwBQI/QatvcuLazu1jRsfSFWsvugmVnavweoP4N7nmalRoyS/Gz2lsPLL3DSOo6bh3V9+y/PegoZ9m3YW7zH/khwCIiDd8/L0u0/KWWXTWSKOv46aGQh6I1SqnoVDzjpIzrNse47Q/ag/zBGnJ/wH+mH5Fct5rL0I+eBvY1PF+bxYXUzFnpacmWDHdItmQFenN+a8rQqS/sCJGXuOzc7Yf7FLx+DiB+qovMRu6Pt9gy8UEYURBX7AKoKXt9jtylPhN+Ui7Yi88UNqOcT4hbPeqpz4EiUjTo9aqRnN1zGwLgcEkgn0EEVTQfZrMh4OhAEZk/iE1w1erQyqfyiA9oHi/eO6S9ewVI0AtXKstCrEGJyLWAAcW/ElQJWD1Y3122gMUtK1TTjzhSqTyOHFa6YYZeJE1fJOlSkUkau84qHYNIT4MHiozEcaDhQWpzLnG+MH88+ZTmgqOM7VaBgBa8MP+9sV12xV56g/kPKYYN60e+9Bs8t7ZhMX5pzWWTitNGaIeaykvuhvaXVyhzv5ACkreuhvK565eUHlP4aFM61LoYm31XsT1EZgteS1uw74Bwz4ce5SQGjKTPHIdMCvDpM8gDkJ09kxvOrePG2JTAbeDPuNpo5PvR79zLhBLgfVqQcVRY40uRTMqAq7OmJmNCzqlW9edc+V0pp7TK+gUYfFqff52I9froKKSmJCsADqsA3p4J4m26Y3PBGFrBzVod56pNBFRH22m/4ehhvzvD+QHXcUEdGp4AnRTXdNFRCE7AFMnRmWMJNDfaC7ZwUbpsS/yGihITnzV2VB7JBGDw8b4s2+1QRwesCnIP+Eky45ZoYgIaLOjjmLbzA+M0V6Ft4a0TdmZRljQ8XJiZWsi+GL9C4mc1+wYjnycU7/QWj0DAvLsPsXLkGatgtOWeD+lWZTBWTjNG7u6CU6wFIYUQuusry2Fk3Z4mWwMbxfXkHAUh/DUpwsz3P9Bje0DER2btvPxboJrNNro2bhL+DK9QwpZyT/C2Et6czIb8IWmSHhH1uMYwMT7GPLBzYUbKv2GvTtpEQxWIyIXAkiBSKcGdZtiIF1DZAYWM0SQY+gXRfFlQK0tbtNEfGQQbhuQqel0yprT8I89ZqFE8EQHPJr6Yj6F8oDQI6buwK67RFEZo2xNItfwJ+D4Jv8LoGMwEfF61PQn34Ok8GIZg+7Q26+eta+fjZMN4wnPAeOxfDBXQA4ZiazcfYjKVlbR2COIpI28u+U8ALFB8YdhxVCqOasVU8DdMbJhy6Rmgt+2CbFdTk1C9BdEx3wD7Bfjiie/rxcjzw8SX20CH7ZNbuVoyc/0CtA3Nb8DH8p5UiM53SO6GEqV0EqaR3o+PAKTdUYD1BZw79AxhOgDGWMbeUqx2M8+Ry8sluovEr5V9r0jnwAApMlmVnXWJTFz3COqusvrnn4uoVPqz7BV+z1VSB8BdWlhD4TELxZGoGeYaVhquPu9DzU+KoV8btCEGxRbGdBOg/oTirXULWXE0bPDhEzr0HKLdrFJIElNp/sGpELD8vISYOfhzHg+MwIOVzP35beJBybsUGFN/pNVZzcepqjA4gyeN9BXLIqyMFbf9oE35u10f/9WMfTa0jROGbHZkh+zOqVN1jAqE56AAAAAQAFWC41MDkAAAKcMIICmDCCAYCgAwIBAgIEeeAXIjANBgkqhkiG9w0BAQUFADANMQswCQYDVQQGEwJjbjAgFw0yMzA2MDExNTE4NDVaGA8yMDUzMDcyMzE1MTg0NVowDTELMAkGA1UEBhMCY24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCuWERR6lH4blHbWARKIEl2KfVt3EzqyuZyi5d20sduIgnUvGseTj4skkeEzx65BqjRFvgNy7If4KjexeZJX7BqxjELiIb71pTcXPxFqOdH0sfW34QDk96xjB0NgBeJolsM5RTuB5Gx8xM2RiCwVDtE8p970oHFTf516C1LwS6ZWSDRA1AEHnQQyA6NJeHKPv9Hytu4mUPIIG4fwR70+zWV6vAGY6xTvTVpeLDsdmWLjJMeA49x3BH3zC2wh8a2WyI/E0mOK2Zf2KEB4TNiacQlCjAIftHlgq55Um+ui5NmASKAXGd4joGGRtXi7lfuIQK00VbeEnsTFHaM+e/ARq6JAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBAHeiiVED/eWhGILykLO3ecNw3CqtKGM8gRbNowcVzCrhl+PZDnUCZFymERlLaa1pARcAdC2gYqqYpyNCcqUN9psuiegItioVjyeLb5b2UQf5+Rsdx154mbWAOSGE0qQxAnAfdEapAx9pDKdSLzNqJe7StQxHBQrXojBthKEL+ByL1sWXlLrf0DnAYqkkz4eSdzLqCsJ8p6b33g2KtIAvKtgGvloiCfVUbRFbWufrryxWxsm1Ty4hPWcmeiOiMOPlu8Bkb7Jy/N+r4b2tNdJrfFSl04Q7Y9WF+1FRskBT0BNf5lf6yLu49NZTVis8Y2VIV9BEUFbtR7s9LJADFEMVyZhEmY761e5wgC/+2J2Zx55Ogtmshw==" | base64 -d > keystore.jks
        chmod 777 *
        ./gradlew assembleRelease
        rm keystore.jks
        echo "APkFileName=$(find app/build/outputs/apk/release -name "*.apk")" >> $GITHUB_ENV
        echo "::set-output name=status::success"
 
    - name: Upload Artefact
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        name: app-release
        path: ${{ env.APkFileName }}

    - name: Upload Artefact to App Center
      if: steps.build.outputs.status == 'success' && !cancelled()
      uses: wzieba/AppCenter-Github-Action@v1.3.2
      with:
        appName: liuran001/gao3-ji1-zhu4-shou3-R
        token: ${{secrets.APP_CENTER_TOKEN}}
        group: '搞机助手·R'
        file: ${{ env.APkFileName }}
        notifyTesters: true
        debug: false
        gitReleaseNotes: true

      # https://github.com/yujincheng08/BiliRoaming/blob/019eb71afa1887a461f7603987c822ea3fd67f88/.github/workflows/android.yml#L50
    - name: Post to channel
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      env:
        CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
        BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        FILE: ${{ github.workspace }}/${{ env.APkFileName }}
        COMMIT_MESSAGE: |+
          New push to github\!
          ```
          ${{ github.event.head_commit.message }}
          ```by `${{ github.event.head_commit.author.name }}`
          See commit detail [here](${{ github.event.head_commit.url }})
          Snapshot apk is attached
      run: |
        ESCAPED=`python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))'`
        curl -v "https://api.telegram.org/bot${{ secrets.BOTTOKEN }}/sendMediaGroup?chat_id=${{ secrets.MESSAGEID }}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22parse_mode%22:%22MarkdownV2%22,%22caption%22:${ESCAPED}%7D%5D"  -F release="@$FILE"
        
    - name: Deploy
      env: 
        GITHUB_REPO: github.com/helloklf/vtools-dev-apks.git
      run: |
        cd ${{ github.workspace }}/app/build/outputs/apk/release/
        git init
        git config user.name "helloklf"
        git config user.email "helloklf@outlook.com"
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push --force --quiet "https://${{ secrets.ACCESS_TOKEN }}@$GITHUB_REPO" master:master
